# DB setting
spring:
  datasource:
    username: ssafy
    password: ssafy

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Wdj4dM5Pe7PzFa_RtC0H
            client-secret: DFW5ITWzk_

          google:
            client-id: 227328243279-8fvee68085idvu0e5kdu1tcfrg3kja36.apps.googleusercontent.com
            client-secret: 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